### ISSUE TITLE
Align documents with SSP system-characteristics constraints

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/automate.fedramp.gov#55]
Align per the feedback https://github.com/GSA/fedramp-automation/pull/610#pullrequestreview-2292745849 to merge those constraints and publish accurate docs.

**Comment by aj-stein-gsa** [comment]
Since I am becoming oh so good and burning down my task list on GitHub, @Rene2mt has rightfully and graciously offered to work on the PR to ensure it gets done sooner or later.

**Comment by Rene2mt** [comment]
@Gabeblis I'm adding as as assignee.

You can reference PR https://github.com/GSA/automate.fedramp.gov/pull/56 if needed, but I think you have newer content in your most recent PRs ( [Add system-characteristics 'information-type' constraints GSA/fedramp-automation#685](https://github.com/GSA/fedramp-automation/pull/685), https://github.com/GSA/automate.fedramp.gov/pull/91) that addresses this issue.

**Comment by aj-stein-gsa** [comment]
So we still need to touch up some other areas, particularly information-types CIA categorization per #689. @Gabeblis, should I create a separate issue for that?

To be fair and self-critical: I made this issue for me to work on a slate of things at the same time and didn't deliver, so there is no clear goals or AC because I knew, at the time, what I wanted to add but that is not any clearer now and there have been a few changes to the doc. So ... let me know.

**Comment by Gabeblis** [comment]
> So we still need to touch up some other areas, particularly information-types CIA categorization per #689. @Gabeblis, should I create a separate issue for that?
> 
> To be fair and self-critical: I made this issue for me to work on a slate of things at the same time and didn't deliver, so there is no clear goals or AC because I knew, at the time, what I wanted to add but that is not any clearer now and there have been a few changes to the doc. So ... let me know.

I do have an [issue](https://github.com/GSA/fedramp-automation/issues/791) and [draft PR](https://github.com/GSA/automate.fedramp.gov/pull/87) currently open for this. That is my fault for dragging a bit on it. I'm working on touching up the documentation now so that I can transition it to ready for review. Just meshing some things together between feedback, what I have, and the documentation you had previously added for system characteristics assemblies in the [(now closed) PR #56](https://github.com/GSA/automate.fedramp.gov/pull/56)
